# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Org.create(name: "Boys and Girls Club", ppname: "Arun Sood", ppphone: "8053381903", ppemail: "arsood@gmail.com", ppskype: "arsood", approved: true, username: "arsood", password: "password", description: "Boys & Girls Clubs of San Francisco believes that every child and teen has the potential to BE GREAT and deserves a chance at a GREAT FUTURE.  Every day, our nine Clubhouses open their doors to youth who need us the most, providing skilled & caring staff, fun & effective programs and first-class facilities in an environment that promotes respect, responsibility and fun.  Boys & Girls Clubs of San Francisco prides itself on empowering youth to reach their full potential, and gain experiences that they wouldn’t otherwise have.  Whether it’s leadership development, opportunities in the arts and sports, homework help, preparing for college or volunteering in the community, our youth members are learning to do better in school, stay physically fit, make healthier lifestyle choices, and be ready for life.  These are the skills they need to BE GREAT and build GREAT FUTURES!", timezone: "America/Los_Angeles", zipcode: 94134, pphandle: "arsood", pphandletype: "Skype")

Org.create(name: "Foundation for Sustainable Development", ppname: "Arun Sood", ppphone: "8053381903", ppemail: "arsood@gmail.com", ppskype: "arsood", approved: true, username: "arsood", password: "password", description: "FSD supports the efforts of grassroots development organizations in Africa, Asia and Latin America that are working to better their communities, environments, and the economic opportunities around them. We believe economic development begins with community development and is only sustainable if it comes from and is supported by the members of these communities. Also, through our programs, we aim to raise international awareness of the economic challenges in developing countries and support cross-cultural communities in finding more effective solutions to development issues.", timezone: "America/Los_Angeles", zipcode: 94134, pphandle: "arsood", pphandletype: "Skype")

Org.create(name: "Endangered Species International", ppname: "Arun Sood", ppphone: "8053381903", ppemail: "arsood@gmail.com", ppskype: "arsood", approved: true, username: "arsood", password: "password", description: "Endangered Species International is strongly committed to reversing the trend of human-induced species extinction, saving endangered animals, and preserving wild places!", timezone: "America/Los_Angeles", zipcode: 94134, pphandle: "arsood", pphandletype: "Skype")

Org.create(name: "Project Homeless Connect", ppname: "Arun Sood", ppphone: "8053381903", ppemail: "arsood@gmail.com", ppskype: "arsood", approved: true, username: "arsood", password: "password", description: "The mission of Project Homeless Connect (PHC) is to connect San Francisco’s homeless with the system of care that will help them move off the streets and into housing.", timezone: "America/Los_Angeles", zipcode: 94134, pphandle: "arsood", pphandletype: "Skype")

Org.create(name: "AIM High", ppname: "Arun Sood", ppphone: "8053381903", ppemail: "arsood@gmail.com", ppskype: "arsood", approved: true, username: "arsood", password: "password", description: "The mission of Aim High is to provide underserved urban youth with challenging, innovative and highly supportive educational programs, most notably our exemplary summer school. The goal of Aim High is to ensure that our students are well-prepared for success in school, have a deep appreciation for their community, and are aware of the issues—personal, local and environmental—that affect their lives. Our vision is to inspire youth to reach for their dreams.", timezone: "America/Los_Angeles", zipcode: 94134, pphandle: "arsood", pphandletype: "Skype")

Org.create(name: "Child Family Health International", ppname: "Arun Sood", ppphone: "8053381903", ppemail: "arsood@gmail.com", ppskype: "arsood", approved: true, username: "arsood", password: "password", description: "Founded in 1992, Child Family Health International is a global family of committed professionals and students who work to strengthen communities at the grassroots level. We are united by a vision of advancing quality healthcare for all by creating global health education programs that are socially responsible and financially just.", timezone: "America/Los_Angeles", zipcode: 94134, pphandle: "arsood", pphandletype: "Skype")